version: '3.8'
services:
 
  db:
    image: mariadb:lts-noble
    ports: 
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_DATABASE: egy_darab
    volumes:
        - ./db:/var/lib/mysql/
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - optcgsim_network
  
  backend:
    tty: true
    stdin_open: true
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    environment:
      - ASPNETCORE_URLS=http://[..]:5000
      - DB_HOST=${DB_HOST}
    restart: unless-stopped
    networks:
      - optcgsim_network
    depends_on:
      db:
        condition: service_healthy

networks:
  optcgsim_network:
    driver: bridge