// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thesis_ASP;

#nullable disable

namespace Thesis_ASP.Migrations
{
    [DbContext(typeof(TCGDbContext))]
    [Migration("20250218162728_AddAttributeColumn")]
    partial class AddAttributeColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Thesis_ASP.Card", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("id"));

                    b.Property<int>("attribute")
                        .HasColumnType("int");

                    b.Property<string>("cardID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cardName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("cardType")
                        .HasColumnType("int");

                    b.Property<int>("characterType")
                        .HasColumnType("int");

                    b.Property<int>("color")
                        .HasColumnType("int");

                    b.Property<int>("cost")
                        .HasColumnType("int");

                    b.Property<int>("counter")
                        .HasColumnType("int");

                    b.Property<string>("effect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("power")
                        .HasColumnType("int");

                    b.Property<string>("trigger")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("cards");

                    b.HasData(
                        new
                        {
                            id = 2L,
                            attribute = 0,
                            cardID = "ST01-002",
                            cardName = "Usopp",
                            cardType = 0,
                            characterType = 0,
                            color = 4,
                            cost = 2,
                            counter = 1000,
                            effect = "effect",
                            power = 2000,
                            trigger = "trigger"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
